name: CMPT_340_Environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.4
  - pytorch
  - torchvision
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - pillow
  - tqdm
  - pip
  - pip:
      - kagglehub
      - opendatasets